import { APP_INITIALIZER, ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors, withFetch } from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { authInitializer } from './core/auth/auth.initializer';
import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  ArrowLeft,
  BarChart2,
  Bell,
  BellRing,
  Calculator,
  Check,
  CheckCircle2,
  ChefHat,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDot,
  CircleMinus,
  CirclePlus,
  ClipboardList,
  Clock,
  DivideCircle,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  Loader2,
  MessageSquare,
  Minus,
  Package,
  PackageX,
  Pencil,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Search,
  SearchX,
  ShoppingBag,
  Star,
  Table2,
  Tag,
  Timer,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  WifiOff,
  X,
  XCircle,
  Zap,
  Menu,
  LogOut,
  LogIn,
  Sun,
  Moon,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(
      withFetch(),
      withInterceptors([authInterceptor])
    ),
    {
      provide: APP_INITIALIZER,
      useFactory: authInitializer,
      multi: true,
    },
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        ArrowLeft,
        BarChart2,
        Bell,
        BellRing,
        Calculator,
        Check,
        CheckCircle2,
        ChefHat,
        ChevronLeft,
        ChevronRight,
        Circle,
        CircleDot,
        CircleMinus,
        CirclePlus,
        ClipboardList,
        Clock,
        DivideCircle,
        Eye,
        EyeOff,
        FileText,
        Flame,
        Inbox,
        LayoutDashboard,
        LayoutGrid,
        Loader2,
        MessageSquare,
        Minus,
        Package,
        PackageX,
        Pencil,
        Play,
        Plus,
        Receipt,
        RefreshCw,
        Search,
        SearchX,
        ShoppingBag,
        Star,
        Table2,
        Tag,
        Timer,
        Trash2,
        TrendingUp,
        Undo2,
        User,
        UserPlus,
        Users,
        Utensils,
        UtensilsCrossed,
        Wallet,
        WifiOff,
        X,
        XCircle,
        Zap,
        Menu,
        LogOut,
        LogIn,
        Sun,
        Moon,
      }),
    },
  ],
};
